version: "3.4"

services:
  nufi:
    image: postgres:12.6-alpine
    environment:
      POSTGRES_DB: hello_django_dev
      POSTGRES_PASSWORD: hello_django
      POSTGRES_USER: hello_django
  herre:
    build: .
    command: sh ./run.sh
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.herreheaders.headers.customrequestheaders.SCRIPT_NAME=/herre"
      - "traefik.http.routers.herre.rule=PathPrefix(`/herre`)"
      - "traefik.http.routers.herre.middlewares=herreheaders"
      - "traefik.http.routers.herre.entrypoints=web"

networks:
  default:
    external:
      name: dev
