version: "3.4"

services:
  snag:
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_DB: hello_django_dev
      POSTGRES_PASSWORD: hello_django
      POSTGRES_USER: hello_django
  herre:
    build: .
    command: sh ./run.sh
    ports:
      - 8000:8000
  ngrok:
    image: wernight/ngrok
    command: ngrok start -config=/opt/ngrok/conf/ngrok.yml herre arkitekt
    ports:
      - 4040:4040
    volumes:
      - ./connector.yaml:/opt/ngrok/conf/ngrok.yml
    links:
      - herre

networks:
  default:
    external:
      name: dev
