# Generated by Django 3.1.7 on 2021-04-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
