# Generated by Django 3.2.2 on 2021-05-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0002_application_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='logo',
        ),
    ]
