# Generated by Django 6.0.6 on 2026-08-20 12:26

import authapp.models
import authlib.oauth2.rfc6749.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('redirect_uri', models.TextField(default='', null=True)),
                ('response_type', models.TextField(default='')),
                ('scope', models.TextField(default='', null=True)),
                ('auth_time', models.IntegerField(default=authapp.models.now_timestamp)),
                ('nonce', models.CharField(default='', max_length=120, null=True)),
                ('code_challenge', models.CharField(blank=True, default='', max_length=128)),
                ('code_challenge_method', models.CharField(blank=True, default='', max_length=10)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.AuthorizationCodeMixin),
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48)),
                ('token_type', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=10000, unique=True)),
                ('refresh_token', models.CharField(blank=True, db_index=True, max_length=10000, null=True, unique=True)),
                ('scope', models.TextField(default='')),
                ('revoked', models.BooleanField(default=False)),
                ('issued_at', models.IntegerField(default=authapp.models.now_timestamp)),
                ('expires_in', models.IntegerField(default=0)),
                ('chain_started_at', models.IntegerField(default=authapp.models.now_timestamp, help_text="When this token's refresh chain began. Copied through rotation, so the 30-day sliding refresh window cannot be extended forever — the whole chain dies at the absolute cap and a human must re-authorize.")),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.TokenMixin),
        ),
    ]
