# Generated by Django 6.0.6 on 2026-08-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karakter.membership'),
        ),
        migrations.AddField(
            model_name='oauth2token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karakter.membership'),
        ),
    ]
