info:
  name: internal
  host: herre:8000

services:
  arkitekt:
    agent:
      endpoint_url: ws://arkitekt:8090/agi/
      instance_id: default
    endpoint_url: http://arkitekt:8090/graphql
    healthz: http://arkitekt:8090/ht
    instance_id: default
    postman:
      endpoint_url: ws://arkitekt:8090/watchi/
      instance_id: default
    secure: false
    ws_endpoint_url: ws://arkitekt:8090/graphql
  fluss:
    endpoint_url: http://fluss:8070/graphql
    ws_endpoint_url: ws://fluss:8070/graphql
    healthz: http://fluss:8070/ht
  herre:
    base_url: http://herre:8000/o
    endpoint_url: http://herre:8000/graphql
    healthz: http://herre:8000/ht
    redirect_uri: http://herre:6767/
    secure: false
  man:
    endpoint_url: http://herre:8000/graphql
    healthz: http://herre:8000/ht
    secure: false
  mikro:
    datalayer:
      access_key: weak_access_key
      endpoint_url: http://mikro:9000
      secret_key: weak_secret_key
      secure: false
    endpoint_url: http://mikro:8080/graphql
    healthz: http://mikro:8080/ht
    secure: false
    ws_endpoint_url: ws://mikro:8080/graphql
  port:
    endpoint_url: http://port:8050/graphql
    healthz: http://port:8050/ht
