info:
  name: p-tnagerl-lab1
  host: p-tnagerl-lab1:8000

services:
  arkitekt:
    agent:
      endpoint_url: ws://p-tnagerl-lab1:8090/agi/
      instance_id: default
    endpoint_url: http://p-tnagerl-lab1:8090/graphql
    healthz: http://p-tnagerl-lab1:8090/ht
    instance_id: default
    postman:
      endpoint_url: ws://p-tnagerl-lab1:8090/watchi/
      instance_id: default
    secure: false
    ws_endpoint_url: ws://p-tnagerl-lab1:8090/graphql
  fluss:
    endpoint_url: http://p-tnagerl-lab1:8070/graphql
    ws_endpoint_url: ws://p-tnagerl-lab1:8070/graphql
    healthz: http://p-tnagerl-lab1:8070/ht
  herre:
    authorization_grant_type: CLIENT_CREDENTIALS
    base_url: http://p-tnagerl-lab1:8000/o
    endpoint_url: http://p-tnagerl-lab1:8000/graphql
    healthz: http://p-tnagerl-lab1:8000/ht
    secure: false
  mikro:
    datalayer:
      access_key: weak_access_key
      endpoint_url: http://p-tnagerl-lab1:9000
      secret_key: weak_secret_key
      secure: false
    endpoint_url: http://p-tnagerl-lab1:8080/graphql
    healthz: http://p-tnagerl-lab1:8080/ht
    secure: false
    ws_endpoint_url: ws://p-tnagerl-lab1:8080/graphql
  port:
    endpoint_url: http://p-tnagerl-lab1:8050/graphql
    healthz: http://p-tnagerl-lab1:8050/ht
  man:
    endpoint_url: http://p-tnagerl-lab1:8000/graphql
    healthz: http://p-tnagerl-lab1:8000/ht
    redirect_uri: http://p-tnagerl-lab1:6767/
    secure: false
