# Generated by Django 6.0.6 on 2026-08-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The identifier of the object. Consult the documentation for the format', max_length=1000)),
                ('object', models.CharField(help_text='The object id of the object, on its associated service', max_length=1000)),
                ('text', models.TextField(help_text='A clear text representation of the rich comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this comment got created')),
                ('descendants', models.JSONField(default=list, help_text='The immediate descendends of the comments. Think typed Rich Representation')),
                ('resolved', models.DateTimeField(blank=True, help_text='Is this comment marked as resolved?', null=True)),
                ('mentions', models.ManyToManyField(blank=True, help_text='The users that got mentioned in this comment', related_name='mentioned_in', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The parent of this comment. Think Thread', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='komment.comment')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='The user that resolved this comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user that created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
