# Generated by Django 3.2.19 on 2023-08-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komment', '0002_auto_20230825_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_identifier',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='object',
        ),
    ]
