# Generated by Django 6.0.6 on 2026-10-10 17:07

import karakter.deeplinks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deeplink_apps',
            field=models.JSONField(blank=True, default=karakter.deeplinks.default_deeplink_apps, help_text="The apps kontrol may forward this organization's deep links to: a list of {protocol, name, install_url, mobile}. The first entry is the default (on a mobile device, the first with `mobile`). Empty switches forwarding off. See karakter.deeplinks for the rules."),
        ),
    ]
