# Generated by Django 6.0.6 on 2026-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='allow_notifications',
            field=models.BooleanField(default=True, help_text="Whether this organization may push notifications to the member's registered devices. Registering a device (in the companion app) is the global consent; this flag is the per-organization mute."),
        ),
    ]
