# Generated by Django 6.0.6 on 2026-08-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0002_membership_allow_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='brand_chroma',
            field=models.FloatField(blank=True, help_text='Personal brand chroma (0–1) this member picked for the organization. Sets how saturated the tint is while this organization is active.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_chroma',
            field=models.FloatField(blank=True, help_text="The organization's default brand chroma (0–1). Members can override it with their own membership brand chroma.", null=True),
        ),
    ]
