# Generated by Django 6.0.6 on 2026-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0002_organization_deeplink_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_link_preview',
            field=models.BooleanField(default=False, help_text="Opt-in: show this organization's name, description and logo on kontrol's link pages to visitors who are not members (or not signed in). Off, a link reveals nothing about the organization it belongs to."),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_link_preview',
            field=models.BooleanField(default=False, help_text="Opt-in: show this user's name and picture on kontrol's link pages when a link they shared names them (`?user_id=`), to visitors who may not be signed in. Only ever shown together with an organization that opted in as well."),
        ),
    ]
