# Generated by Django 6.0.6 on 2026-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0003_membership_brand_chroma_organization_brand_chroma'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access_token_lifetime',
            field=models.IntegerField(blank=True, default=None, help_text="Access-token lifetime in seconds for tokens issued to this organization's clients. None means the server default (authapp.server.ACCESS_TOKEN_EXPIRES_IN, one hour). Clamped into [MIN_ACCESS_TOKEN_EXPIRES_IN, MAX_ACCESS_TOKEN_EXPIRES_IN] at token generation, so a stale or oversized value can never outlive the cap.", null=True),
        ),
    ]
