# Generated by Django 3.2.16 on 2022-12-16 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faktapplication',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faktapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fakt_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='infos.configurationgraph'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationelement',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='infos.configurationgraph'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('identifier', 'version'), name='Only one per identifier and version'),
        ),
        migrations.AddConstraint(
            model_name='faktapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['website', 'desktop'])), fields=('app', 'application'), name='Only one unique app per identifier and version'),
        ),
        migrations.AddConstraint(
            model_name='faktapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['user'])), fields=('app', 'application', 'user'), name='Only one unique app per identifier and version if it is a user app'),
        ),
    ]
