# Generated by Django 3.2.12 on 2022-05-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('infos', '0002_auto_20220516_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('scopes', models.JSONField(default=list)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='infos.configurationgraph')),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='infos.configurationgraph')),
            ],
        ),
    ]
