# Generated by Django 3.2.19 on 2023-05-06 11:06

from django.db import migrations, models
import django.db.models.deletion
import infos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_auto_20230502_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('body', models.TextField(validators=[infos.validators.is_valid_jinja2_template])),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('method', models.CharField(choices=[('host_regex', 'Host matches regex'), ('host_is', 'Host is'), ('host_is_not', 'Host is not'), ('port_is', 'Port is'), ('port_is_not', 'Port is not'), ('version_is', 'Version is'), ('version_is_not', 'Version is not'), ('version_regex', 'Version matches regex'), ('identifier_is', 'Identifier is'), ('identifier_is_not', 'Identifier is not'), ('identifier_regex', 'Identifier matches regex')], max_length=1000)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='Only one release per user',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('release', 'user'), name='Only one release per user ()'),
        ),
        migrations.AddField(
            model_name='linker',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkers', to='infos.configurationtemplate'),
        ),
        migrations.AddField(
            model_name='filter',
            name='linker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='infos.linker'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='infos.configurationtemplate'),
        ),
    ]
