# Generated by Django 3.2.12 on 2022-05-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_configurations_devicecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='infos.configurationgraph'),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
