# Generated by Django 3.2.19 on 2023-05-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20230506_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='infos.configurationtemplate'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='method',
            field=models.CharField(choices=[('host_regex', 'Host matches regex'), ('host_is', 'Host is'), ('host_is_not', 'Host is not'), ('port_is', 'Port is'), ('port_is_not', 'Port is not'), ('version_is', 'Version is'), ('version_is_not', 'Version is not'), ('version_regex', 'Version matches regex'), ('identifier_is', 'Identifier is'), ('identifier_is_not', 'Identifier is not'), ('identifier_regex', 'Identifier matches regex')], max_length=1000),
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
