# Generated by Django 3.2.19 on 2023-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_auto_20230506_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='configuration',
        ),
        migrations.AlterField(
            model_name='configurationtemplate',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='method',
            field=models.CharField(choices=[('host_regex', 'Host matches regex'), ('host_is', 'Host is'), ('host_is_not', 'Host is not'), ('port_is', 'Port is'), ('port_is_not', 'Port is not'), ('version_is', 'Version is'), ('version_is_not', 'Version is not'), ('version_regex', 'Version matches regex'), ('identifier_is', 'Identifier is'), ('identifier_is_not', 'Identifier is not'), ('identifier_regex', 'Identifier matches regex')], max_length=1000),
        ),
    ]
