# Generated by Django 3.2.19 on 2023-05-06 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_alter_filter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 5, 6, 13, 30, 33, 208504), max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configurationtemplate',
            name='body',
            field=models.TextField(),
        ),
    ]
