# Generated by Django 3.2.16 on 2022-11-14 14:56

from django.db import migrations, models
import lord.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, storage=lord.storage.PrivateAvatarStorage(), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='groupimage',
            name='image',
            field=models.ImageField(storage=lord.storage.PrivateAvatarStorage(), upload_to=''),
        ),
    ]
