# Generated by Django 3.1.7 on 2021-05-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herreuser',
            name='roles',
        ),
    ]
