# Generated by Django 3.2.14 on 2022-07-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lord', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='auth.group')),
            ],
        ),
    ]
