# Generated by Django 3.2.16 on 2022-11-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lord', '0002_auto_20221114_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lord.herreuser'),
            preserve_default=False,
        ),
    ]
