# Generated by Django 3.2.14 on 2022-07-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lord', '0003_groupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimage',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupimage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auth.group'),
        ),
    ]
