# Generated by Django 6.0.6 on 2026-08-20 12:26

import authlib.oauth2.rfc6749.models
import django_choices_field.fields
import fakts.enums
import fakts.fields
import fakts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('identifier', fakts.fields.IdentifierField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default=fakts.models.generate_client_id, max_length=48, unique=True)),
                ('client_secret', models.CharField(blank=True, default='', help_text='Empty for public clients (every fakts-provisioned client). Only relying parties are confidential.', max_length=120)),
                ('redirect_uris', models.TextField(blank=True, default='')),
                ('scope', models.TextField(blank=True, default='', help_text='Space-separated scope this client may request; written at accept from the granted org scopes.')),
                ('token_endpoint_auth_method', models.CharField(default='none', max_length=48)),
                ('grant_types', models.TextField(default='')),
                ('response_types', models.TextField(blank=True, default='')),
                ('id_token_signed_response_alg', models.CharField(default='RS256', max_length=48)),
                ('membership_is_subject', models.BooleanField(default=False, help_text='Use the membership id as the OIDC `sub` claim instead of the user id. See authapp.oidc_claims.resolve_sub.')),
                ('email_template', models.CharField(blank=True, help_text="Template for the OIDC `email` claim rendered from membership variables (e.g. '{username}@corp.example'). When blank, the user's own email is used. See authapp.oidc_claims.resolve_email.", max_length=500, null=True)),
                ('functional', models.BooleanField(default=True)),
                ('name', models.CharField(default='No name', max_length=1000)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('website', 'WEBSITE (Value represent WEBSITE)'), ('development', 'DEVELOPMENT (Value represent DEVELOPMENT)'), ('desktop', 'DESKTOP (Value represent DESKTOP Aüü)'), ('hub', "HUB (a hub server's identity)"), ('relying_party', 'RELYING_PARTY (a config-provisioned OIDC relying party)')], choices_enum=fakts.enums.ClientKindChoices, default='development', help_text='What kind of principal this client is.', max_length=13)),
                ('role', django_choices_field.fields.TextChoicesField(choices=[('interface', 'INTERFACE (Value represent INTERFACE)'), ('agent', 'AGENT (Value represent AGENT)')], choices_enum=fakts.enums.ClientRoleChoices, default='interface', help_text='Operational role: human INTERFACE vs autonomous task-receiving AGENT.', max_length=9)),
                ('public', models.BooleanField(default=False)),
                ('public_sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirements_hash', models.CharField(blank=True, default='', max_length=1000)),
                ('statuses', models.JSONField(default=dict, help_text="Per-requirement grant outcomes: {'key': 'granted'|'denied'|'unavailable'}.")),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.JSONField(default=dict)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.ClientMixin),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=1000)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('app', 'APP (an app/client registration)'), ('hub', 'HUB (a whole-hub provisioning)')], choices_enum=fakts.enums.DeviceCodeKindChoices, default='app', help_text='What accepting this code produces: an app client or a whole hub.', max_length=3)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('secret', models.CharField(default=fakts.models.generate_device_secret, help_text='The full-entropy device_code polled at the token endpoint. Distinct from `code`, the short human-transcribable user code shown in the configure URL — a shoulder-surfed user code must not be a polling secret.', max_length=100, unique=True)),
                ('granted_scope', models.TextField(default='', help_text="Space-separated scope granted at accept; becomes the token request's scope.")),
                ('interval', models.IntegerField(default=5, help_text='Minimum polling interval in seconds (RFC 8628).')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('staging_manifest', models.JSONField(default=dict, help_text='The app Manifest or HubManifest staged at start.')),
                ('expires_at', models.DateTimeField()),
                ('denied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('identifier', fakts.fields.IdentifierField(max_length=1000)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('token', models.CharField(default=uuid.uuid4, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the alias', max_length=1000, null=True)),
                ('host', models.CharField(blank=True, help_text="The host of the alias, if its a ABSOLUTE alias (e.g. 'example.com'). If not set, the alias is relative to the layer's domain.", max_length=1000, null=True)),
                ('port', models.IntegerField(blank=True, help_text='The port of the alias', null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('absolute', 'ABSOLUTE (Value represent ABSOLUTE)'), ('relative', 'RELATIVE (Value represent RELATIVE)')], choices_enum=fakts.enums.AliasKindChoices, default='relative', help_text="The kind of alias. If relative, the alias is relative to the layer's domain. If absolute, the alias is an absolute URL.", max_length=8)),
                ('ssl', models.BooleanField(default=True, help_text='If the alias is available over SSL or not. If not set, the alias is assumed to be available over SSL.')),
                ('public', models.BooleanField(default=False, help_text="If the alias is publicly reachable. If true, the coordination server can also check the alias's health directly (in addition to client-side reports), which allows checking its health from the kontrol interface.")),
                ('challenge', models.TextField(default='ht', help_text='"A challenge URL to verify the alias on the client. If it returns a 200 OK, the alias is valid. It can additionally return a JSON object with a `challenge\n        key that contains the challenge to be solved by the client.')),
                ('path', models.CharField(blank=True, help_text='The path of the alias,', max_length=1000, null=True)),
                ('scope', models.CharField(default='local', help_text="The scope of the alias. 'local' means that the alias is only available within the local network. 'network' means that the alias is available within the organization's network.", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InstancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allow', 'ALLOW'), ('deny', 'DENY')], help_text='Allow or deny access', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IonscaleAuthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ephemeral', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('identifier', fakts.fields.IdentifierField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('dns_probe', models.TextField(blank=True, default='No probe available', null=True)),
                ('get_probe', models.TextField(blank=True, default='No probe available', null=True)),
                ('kind', models.CharField(help_text='The kind of layer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KommunityPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('short_description', models.CharField(blank=True, max_length=280, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('identifier', fakts.fields.IdentifierField(max_length=1000, unique=True)),
                ('auth_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('license_agreement', models.TextField(blank=True, help_text='Optional license agreement text shown before connecting this partner.', null=True)),
                ('pre_authorize_hook', models.CharField(blank=True, help_text='Optional hook called after creating a partner hub. The response must explicitly approve the hub.', max_length=1000, null=True)),
                ('pre_authorize_token', models.CharField(blank=True, help_text='Optional bearer token sent to the pre-authorize hook.', max_length=1000, null=True)),
                ('partner_kind', models.CharField(choices=[('preauthorized', 'PREAUTHORIZED'), ('oauth2', 'OAUTH_FLOW')], help_text='The kind of partner', max_length=50)),
                ('kommunity_kind', models.CharField(choices=[('open', 'OPEN'), ('restricted', 'RESTRICTED'), ('private', 'PRIVATE')], help_text='The kind of kommunity', max_length=50)),
                ('auto_configure', models.BooleanField(default=False)),
                ('preconfigured_hub', models.JSONField(blank=True, help_text='A preconfigured hub that gets created when a user redeems a token from this partner.', null=True)),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Filter conditions to determine which users/organizations this partner applies to. Example: {'email_domain_equals': ['example.com', 'test.org'], 'email_domain_ends_with': ['edu']}", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MeshDeviceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('challenge_code', models.CharField(max_length=100, unique=True)),
                ('requested_machine_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('staging_ephemeral', models.BooleanField(default=False)),
                ('staging_tags', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('denied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('manifest_hash', models.CharField(blank=True, help_text='SHA-256 hash of the manifest this token was first redeemed with. Used to detect manifest changes on re-redeem.', max_length=64, null=True)),
                ('allow_reredeem', models.BooleanField(default=False, help_text='If set, this token may be re-redeemed even when the manifest hash differs from the originally redeemed one.')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', fakts.fields.VersionField(max_length=1000)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_dev', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1000)),
                ('scopes', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional', models.BooleanField(default=True)),
                ('alias_reports', models.JSONField(default=dict, help_text='Raw snapshot of the reported payload: {key: {alias_id, valid, reason}}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('identifier', fakts.fields.IdentifierField(max_length=1000)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(default='default', max_length=1000)),
                ('private_key', models.TextField(blank=True, help_text='The private key of the instance, used for signing claims.', null=True)),
                ('template', models.TextField()),
                ('public_key', models.TextField(blank=True, help_text='The public key of the instance, if applicable.', null=True)),
                ('token', models.CharField(help_text='The token of the instance, used for authentication.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstanceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', fakts.fields.VersionField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TailscaleInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UsedAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=1000)),
                ('reason', models.TextField(blank=True, null=True)),
                ('used_at', models.DateTimeField(auto_now=True, help_text='When the client last reported this usage.')),
            ],
        ),
    ]
