# Generated by Django 6.0.6 on 2026-08-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fakts', '0001_initial'),
        ('karakter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='app',
            name='organization',
            field=models.ForeignKey(help_text='The organization this app registration belongs to — the same identifier in two organizations is two registrations.', on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='client',
            name='membership',
            field=models.ForeignKey(blank=True, help_text='The (user, organization) this client acts for. Null means not yet approved (staged) or a global relying party.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='karakter.membership'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Denormalized from membership (carries constraints and tenant scoping). Null for staged rows and global relying parties.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='clients', to='karakter.scope'),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='fakts.device'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='client',
            field=models.OneToOneField(help_text='The unified client dynamically registered at start — the staged row itself. Approval binds it in place; the code is burned at token issuance.', on_delete=django.db.models.deletion.CASCADE, related_name='device_code', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization the code was accepted into. Null while pending.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_codes', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_groups',
            field=models.ManyToManyField(blank=True, related_name='devices', to='fakts.devicegroup'),
        ),
        migrations.AddField(
            model_name='hub',
            name='client',
            field=models.OneToOneField(blank=True, help_text="The hub server's identity (a public unified Client, bound at hub device-code accept). Hub servers poll the token endpoint as this client and receive their config in the token response envelope. Null for hubs provisioned outside the device-code flow (e.g. partner auto-configuration), which still use `token` + /f/claimhub/. Distinct from `Client.hub` — the hub an *app* client composes against.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_identity', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='hub',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_hubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hub',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fakts.hub'),
        ),
        migrations.AddField(
            model_name='instancepermission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_permissions', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='instancepermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ionscaleauthkey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ionscale_auth_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ionscaleauthkey',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ionscale_auth_keys', to='fakts.hub'),
        ),
        migrations.AddField(
            model_name='hub',
            name='auth_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs', to='fakts.ionscaleauthkey'),
        ),
        migrations.CreateModel(
            name='IonscaleLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fakts.layer')),
                ('tailnet_name', models.CharField(max_length=1000, unique=True)),
                ('magic_dns_enabled', models.BooleanField(default=True)),
                ('https_enabled', models.BooleanField(default=True)),
            ],
            bases=('fakts.layer',),
        ),
        migrations.AddField(
            model_name='layer',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='layer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='instancealias',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='fakts.layer'),
        ),
        migrations.AddField(
            model_name='kommunitypartner',
            name='oauth_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kommunity_partners', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='linkinspector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_inspectors', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='meshdevicecode',
            name='auth_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesh_device_code', to='fakts.ionscaleauthkey'),
        ),
        migrations.AddField(
            model_name='meshdevicecode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_client', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='fakts.hub'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='fakts.app'),
        ),
        migrations.AddField(
            model_name='release',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='client',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fakts.release'),
        ),
        migrations.AddField(
            model_name='report',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_healthy_report',
            field=models.ForeignKey(blank=True, help_text='The most recent report where the client was functional; null if it has never reported healthy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fakts.report'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(help_text='The organization this service registration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='allowed_instances', to='auth.group'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_organizations',
            field=models.ManyToManyField(related_name='allowed_instances', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='denied_groups',
            field=models.ManyToManyField(related_name='denied_instances', to='auth.group'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='denied_users',
            field=models.ManyToManyField(related_name='denied_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to='fakts.device'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='fakts.hub'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns this instance. If null the instance is global.', on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='steward',
            field=models.ForeignKey(help_text='The user who is responsible for this instance. If null the admin is stewared by admin user.', on_delete=django.db.models.deletion.CASCADE, related_name='stewarded_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instancepermission',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='instancealias',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='serviceinstancemapping',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='serviceinstancemapping',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='servicerelease',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='fakts.service'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='fakts.servicerelease'),
        ),
        migrations.AddField(
            model_name='tailscaleinspector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailscale_inspectors', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='usedalias',
            name='alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='fakts.instancealias'),
        ),
        migrations.AddField(
            model_name='usedalias',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_aliases', to='fakts.client'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier'), name='Only one app identifier per organization'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('node_id', 'organization'), name='Only one node_id per organization'),
        ),
        migrations.AddConstraint(
            model_name='hub',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier'), name='Only one hub identifier per organization'),
        ),
        migrations.AddField(
            model_name='ionscaleauthkey',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_keys', to='fakts.ionscalelayer'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('app', 'version'), name='Only one per app and version'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('release', 'membership', 'node'), name='Only one client per release, membership and node'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier'), name='Only one service identifier per organization'),
        ),
        migrations.AddConstraint(
            model_name='instancealias',
            constraint=models.UniqueConstraint(fields=('instance', 'host', 'port', 'ssl', 'path', 'kind'), name='Only one alias per instance host port ssl path kind'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstancemapping',
            constraint=models.UniqueConstraint(fields=('key', 'client'), name='Only one instance per key and hub'),
        ),
        migrations.AddConstraint(
            model_name='servicerelease',
            constraint=models.UniqueConstraint(fields=('service', 'version'), name='Only one per service and version'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstance',
            constraint=models.UniqueConstraint(fields=('release', 'instance_id', 'organization', 'device', 'hub'), name='Only one instance_id per release, organization and device and instance'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstance',
            constraint=models.UniqueConstraint(fields=('token', 'hub'), name='Only one token per hub'),
        ),
    ]
