# Generated by Django 6.0.6 on 2026-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='Only one client per release, membership and node',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('release', 'membership', 'node', 'hub'), name='Only one client per release, membership, node and hub'),
        ),
    ]
