# Generated by Django 6.0.6 on 2026-08-20 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0003_client_unique_per_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=1000, unique=True),
        ),
    ]
