# Generated by Django 6.0.6 on 2026-08-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0004_hub_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtoken',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, help_text='How many times this token may be redeemed. NULL means unlimited. Each redeem mints a fresh access+refresh pair, so an unlimited, never-expiring token is a permanent foothold for whoever holds it.', null=True),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='redemption_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this token has been redeemed so far.'),
        ),
    ]
