# Generated by Django 6.0.6 on 2026-08-21 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0005_redeemtoken_max_redemptions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latest_report_resolved',
            field=models.BooleanField(default=False, help_text="Has an operator acknowledged the client's most recent report? Denormalised from Report.resolved_at (like `functional` itself) so the dashboard can list clients needing attention with a plain indexed filter. Cleared by every incoming report, so a client that is still broken comes back onto the list."),
        ),
        migrations.AddField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True, help_text='Optional note from the operator explaining how the report was dealt with.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When an operator acknowledged this report; null while it still needs attention.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='The member who acknowledged this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
