# Generated by Django 6.0.6 on 2026-09-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0006_client_latest_report_resolved_report_resolution_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='report_requested_at',
            field=models.DateTimeField(blank=True, help_text='When an operator asked this client to re-report its configuration; null when nothing is pending. While set, every token response for this client carries `please_report: true` (see authapp.fakts_grants.FaktsEnvelopeMixin), so the client re-reports on its next hourly refresh at the latest. Cleared by the incoming report (fakts.services.clients.report_client).', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='report_requested_by',
            field=models.ForeignKey(blank=True, help_text="The operator who asked for the report; kept for the dashboard's audit trail.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_client_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
