# Generated by Django 6.0.6 on 2026-09-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0007_client_report_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='membership_is_subject',
        ),
    ]
