# Generated by Django 6.0.6 on 2026-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0008_remove_client_membership_is_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='require_nonce',
            field=models.BooleanField(default=False, help_text='Reject an authorization-code request from this client that carries no `nonce`. OIDC Core §3.1.2.1 makes `nonce` OPTIONAL for the code flow, and no discovery field can advertise a stricter rule, so this is a deliberate non-standard tightening that has to be agreed with the relying party out of band — hence per-client and off by default. Only meaningful for the handful of rows provisioned as OIDC relying parties from `openid_apps`: the clients minted dynamically by the device-code and redeem paths never run the code flow at all.'),
        ),
    ]
