# Generated by Django 6.0.6 on 2026-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0009_client_require_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtoken',
            name='pinned_manifest',
            field=models.JSONField(blank=True, help_text='The manifest this token was pre-authorized for, fixed at mint time. When set, a redeem must present the same identifier, version and node_id, and may request only a subset of the pinned scopes and requirements; anything else is refused before a client is provisioned. NULL means the token is unpinned and the manifest is fixed on first redeem (manifest_hash) instead.', null=True),
        ),
    ]
