# Generated by Django 6.0.6 on 2026-09-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0010_redeemtoken_pinned_manifest'),
        ('karakter', '0005_drop_pak_and_komment'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecode',
            name='request_auth_key',
            field=models.BooleanField(default=False, help_text='The app asked for a pre-authorized mesh key (app codes only; hubs ask in their manifest).'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='auth_key',
            field=models.ForeignKey(blank=True, help_text="Mesh key minted at accept for an app that set `request_auth_key`. Handed out once, in the device-code grant's token response, and gone with the burned code.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_device_code', to='fakts.ionscaleauthkey'),
        ),
        migrations.CreateModel(
            name='AppMeshEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_enrollments', to='fakts.app')),
                ('auth_key', models.ForeignKey(blank=True, help_text='The currently live key; the previous one is revoked in ionscale on re-grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_mesh_enrollments', to='fakts.ionscaleauthkey')),
                ('device', models.ForeignKey(blank=True, help_text='The device the app runs on. Without one, nodes are never pruned: two installations on different machines would be indistinguishable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh_enrollments', to='fakts.device')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_mesh_enrollments', to='karakter.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_mesh_enrollments', to='karakter.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'app', 'device'), name='One mesh enrollment per membership, app and device', nulls_distinct=False)],
            },
        ),
    ]
