# Generated by Django 6.0.6 on 2026-09-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0011_app_mesh_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='last_healthy',
            field=models.BooleanField(blank=True, help_text="Whether the hub's last health report said it was healthy.", null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the hub last reported its health (/f/hubhealth/).', null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='mesh_connected',
            field=models.BooleanField(blank=True, help_text="Whether the hub's last health report said its node is on the mesh (null: not reported).", null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='mesh_host',
            field=models.CharField(blank=True, default='', help_text="The hub node's MagicDNS name (or mesh IP), as last reported by the hub.", max_length=1000),
        ),
        migrations.AddField(
            model_name='hub',
            name='version',
            field=models.CharField(blank=True, default='', help_text='The hub software version, as last reported.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='auth_key',
            field=models.ForeignKey(blank=True, help_text="Mesh key minted at accept for an app that set `request_auth_key` (or a hub whose manifest did). Handed out once, in the device-code grant's token response, and gone with the burned code.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_device_code', to='fakts.ionscaleauthkey'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='auth_key',
            field=models.ForeignKey(blank=True, help_text="The hub's currently live mesh key (rotated on every re-authorization).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs', to='fakts.ionscaleauthkey'),
        ),
        migrations.AlterField(
            model_name='redeemtoken',
            name='pinned_manifest',
            field=models.JSONField(blank=True, help_text='The manifest this token was pre-authorized for, fixed at mint time. When set, a redeem must present the same identifier, version and device_id, and may request only a subset of the pinned scopes and requirements; anything else is refused before a client is provisioned. NULL means the token is unpinned and the manifest is fixed on first redeem (manifest_hash) instead.', null=True),
        ),
        migrations.CreateModel(
            name='HubHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthy', models.BooleanField()),
                ('payload', models.JSONField(default=dict, help_text='The raw HubHealthReport.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='fakts.hub')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
