# Generated by Django 6.0.6 on 2026-09-28 10:33

import django.db.models.deletion
import fakts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0012_hub_mesh_and_health'),
        ('karakter', '0005_drop_pak_and_komment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_identifier', fakts.fields.IdentifierField(help_text='The app (by identifier, within the organization) allowed to provision under this mandate.', max_length=1000)),
                ('subject_manifest', models.JSONField(help_text='The manifest the grantor approved (identifier, version, scopes, requirements). Copied as the pin into every provisioned token.')),
                ('attestation', models.CharField(blank=True, default='', help_text='Opaque binding set by the approving service (e.g. a release digest). lok stores it; the agent checks it.', max_length=1000)),
                ('max_clients', models.PositiveIntegerField(blank=True, help_text='How many live clients (plus outstanding tokens) may exist under this mandate. Null means unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this, no new clients may be provisioned. Existing ones keep running.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agent_device', models.ForeignKey(blank=True, help_text='If set, only an agent client running on this device may provision.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_mandates', to='fakts.device')),
                ('agent_membership', models.ForeignKey(blank=True, help_text='If set, only an agent client acting as this membership may provision.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_mandates', to='karakter.membership')),
                ('hub', models.ForeignKey(help_text='The hub provisioned clients compose against.', on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='fakts.hub')),
                ('membership', models.ForeignKey(help_text='The grantor: every client provisioned under this mandate acts as this membership.', on_delete=django.db.models.deletion.CASCADE, related_name='granted_mandates', to='karakter.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='karakter.organization')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='mandate',
            field=models.ForeignKey(blank=True, help_text='The mandate this client was provisioned under. Revoking the mandate deletes the client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fakts.mandate'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='mandate',
            field=models.ForeignKey(blank=True, help_text='The mandate this token was provisioned under, if any. The client it produces is stamped with it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeem_tokens', to='fakts.mandate'),
        ),
    ]
