# Generated by Django 6.0.6 on 2026-10-01 10:52

import django_choices_field.fields
import fakts.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0013_mandates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancealias',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('absolute', 'ABSOLUTE (Value represent ABSOLUTE)'), ('relative', 'RELATIVE (Value represent RELATIVE)'), ('mesh', 'MESH (Value represent MESH)'), ('docker', "DOCKER (only reachable from inside the hub's own docker environment)")], choices_enum=fakts.enums.AliasKindChoices, default='relative', help_text="The kind of alias. If relative, the alias is relative to the layer's domain. If absolute, the alias is an absolute URL. If mesh, it resolves to its hub node on the organization's mesh. If docker, it is only reachable from inside the hub's own docker environment.", max_length=8),
        ),
    ]
