# Generated by Django 6.0.6 on 2026-10-01 11:19

import django_choices_field.fields
import fakts.enums
from django.db import migrations, models


def drop_relative_aliases(apps, schema_editor):
    """Retire the ``relative`` kind: a relative alias with a stored host becomes
    an absolute one at that host; one without a host (or one that would only
    duplicate an existing absolute alias) is deleted, with its usage reports.

    Raw SQL on purpose: the historical ``kind`` field still points at the live
    ``AliasKindChoices``, which no longer has the member, so loading or
    filtering a relative row through the ORM raises.
    """
    quote = schema_editor.connection.ops.quote_name
    alias = quote(apps.get_model("fakts", "InstanceAlias")._meta.db_table)
    usage = quote(apps.get_model("fakts", "UsedAlias")._meta.db_table)

    doomed = f"""
        SELECT r.id FROM {alias} r
        WHERE r.kind = 'relative' AND (
            r.host IS NULL OR r.host = ''
            OR EXISTS (
                SELECT 1 FROM {alias} a
                WHERE a.kind = 'absolute'
                  AND a.instance_id = r.instance_id
                  AND a.host = r.host
                  AND a.ssl = r.ssl
                  AND a.port IS NOT DISTINCT FROM r.port
                  AND a.path IS NOT DISTINCT FROM r.path
            )
        )
    """
    with schema_editor.connection.cursor() as cursor:
        # The usage FK cascades in the ORM only, not in the database.
        cursor.execute(f"DELETE FROM {usage} WHERE alias_id IN ({doomed})")
        cursor.execute(f"DELETE FROM {alias} WHERE id IN ({doomed})")
        cursor.execute(f"UPDATE {alias} SET kind = 'absolute' WHERE kind = 'relative'")


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0014_alias_kind_docker'),
    ]

    operations = [
        # Before the choices change, so no row is left with a kind the field rejects.
        migrations.RunPython(drop_relative_aliases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='instancealias',
            name='host',
            field=models.CharField(blank=True, help_text="The host of the alias (e.g. 'example.com'). Not set for a mesh alias, which resolves to its hub node on the organization's mesh.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instancealias',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('absolute', 'ABSOLUTE (Value represent ABSOLUTE)'), ('mesh', 'MESH (Value represent MESH)'), ('docker', "DOCKER (only reachable from inside the hub's own docker environment)")], choices_enum=fakts.enums.AliasKindChoices, default='absolute', help_text="The kind of alias. If absolute, the alias is an absolute URL. If mesh, it resolves to its hub node on the organization's mesh. If docker, it is only reachable from inside the hub's own docker environment.", max_length=8),
        ),
    ]
